default:
    synapse_opts:
        synID:
            parent_output: "syn25258905"
            tbl: "syn12514611" 
        output_filename: "annotator_test.tsv"
        column_target:
            choice_1: "walk_motion.json"
        unique_identifier: "recordId" # unique identifier for that file in synapse table
        n_batch: 5
        keep_metadata:
            choice_1: "healthCode"
            choice_2: "createdOn"
            choice_3: "phoneInfo"
    survey_opts:
        survey_1:
            colname: "walk_status"
            type: "radio"
            prompt: "Can you guess this user's gait?"
            input_choices: 
                choice_1: "Walking"
                choice_2: "Mostly Walking"
                choice_3: "Some Walking"
                choice_4: "Not Walking"
                choice_5: "Can't Tell"
        survey_2:
            colname: "pocket_status"
            type: "radio"
            prompt: "Is this phone inside the pocket?"
            input_choices:
                choice_1: "In Pocket"
                choice_2: "Partially in Pocket"
                choice_3: "Not in Pocket"
                choice_4: "Can't Tell"
        survey_3:
            colname: "walk_type"
            type: "select"
            prompt: "Walking type?"
            input_choices:
                choice_1: "limping"
                choice_2: "limping2"
                choice_3: "jumping"
                choice_4: "running"
        survey_4:
            colname: "test_type"
            type: "select"
            prompt: "Walking type?"
            input_choices:
                choice_1: "limping"
                choice_2: "limping2"
                choice_3: "jumping"
                choice_4: "running"
        
