default:
    synapse_opts:
        synID:
            parent_output: "syn25672221"
            tbl: "syn25687737" 
        output_filename: "AnnotatedGaitSensor_concord_comparison.tsv"
        column_target:
            - "walk_motion.json"
        unique_identifier: 
            - "recordId"
        n_batch: 50
        keep_metadata:
            - "healthCode"
            - "createdOn"
            - "phoneInfo"
            - "diagnosis"
            - "walk_status_Larsson"
            - "walk_status_Aryton"
            - "walk_status_Elias"
        sort_keys:
            - "recordId"
    survey_opts:
        survey_1:
            colname: "walk_status"
            type: "radio"
            prompt: "Can you guess this user's gait?"
            input_choices: 
                Walking: "Walking"
                Mostly Walking: "Mostly Walking"
                Some Walking: "Some Walking"
                Not Walking: "Not Walking"
                Can't Tell: "Can't Tell"
        survey_2:
            colname: "pocket_status"
            type: "radio"
            prompt: "Is this phone inside the pocket?"
            input_choices:
                In Pocket: "In Pocket"
                Partially in Pocket: "Partially in Pocket"
                Not in Pocket: "Not in Pocket"
                Can't Tell: "Can't Tell"
    image_opts: 
        width: "750px"
        height: "450px"
