default:
    synapse_opts:
        synID:
            parent_output: "syn25258905"
            tbl: "syn22281750" 
        output_filename: "annotator_psorcast_test.tsv"
        column_targets:
            choice_1: "summaryImage.jpg"
        unique_identifier: "recordId" # unique identifier for that file in synapse table
        n_batch: 5
        keep_metadata:
            choice_1: "participantID"
            choice_2: "createdOn"
    survey_opts:
        survey_1:
            colname: "mutilans"
            type: "select"
            prompt: "Mark the mutilans"
            input_choices:
                choice_1: "L1"
                choice_2: "L2"
                choice_3: "L3"
                choice_4: "L4"
                choice_5: "L5"
