default:
    synapse_opts:
        synID:
            parent_output: "syn22311179"
            tbl: "syn22281750" 
        output_filename: "annotator_psorcast_test.tsv"
        column_targets:
            - "summaryImage.jpg"
        unique_identifier: 
            - "recordId"
        n_batch: 5
        keep_metadata:
            - "participantID"
            - "createdOn"
    survey_opts:
        survey_1:
                colname: "is_image_valid"
                type: "radio"
                prompt: "Are you able to rate this image?"
                input_choices:
                    - "Yes"
                    - "No"
        survey_2:
            colname: "left_nail_psoriasis"
            type: "select"
            prompt: "Select Left-Side Nail Psoriasis:"
            input_choices:
                L-1: "L1"
                L-2: "L2"
                L-3: "L3"
                L-4: "L4"
                L-5: "L5"
        survey_3:
            colname: "right_nail_psoriasis"
            type: "select"
            prompt: "Select Right-Side Nail Psoriasis:"
            input_choices:
                R-1: "R1"
                R-2: "R2"
                R-3: "R3"
                R-4: "R4"
                R-5: "R5"
        survey_4:
            colname: "rating_score"
            type: "slider"
            prompt: "rate:"
            input_choices:
                choice_min: 1
                choice_max: 10
                increments: 1
