default:
    synapse_opts:
        synID:
            parent_output: "syn22311179"
            tbl: "syn22281750" 
        output_filename: "annotator_psorcast_test.tsv"
        column_targets:
            choice_1: "summaryImage.jpg"
        unique_identifier: "recordId"
        n_batch: 5
        keep_metadata:
            choice_1: "participantID"
            choice_2: "createdOn"
    survey_opts:
        survey_1:
                colname: "is_image_valid"
                type: "radio"
                prompt: "Are you able to rate this image?"
                input_choices:
                    choice_1: "Yes"
                    choice_2: "No"
        survey_2:
            colname: "left_nail_psoriasis"
            type: "select"
            prompt: "Select Left-Side Nail Psoriasis:"
            input_choices:
                choice_1: "L1"
                choice_2: "L2"
                choice_3: "L3"
                choice_4: "L4"
                choice_5: "L5"
        survey_3:
            colname: "right_nail_psoriasis"
            type: "select"
            prompt: "Select Right-Side Nail Psoriasis:"
            input_choices:
                choice_1: "R1"
                choice_2: "R2"
                choice_3: "R3"
                choice_4: "R4"
                choice_5: "R5"
        survey_4:
            colname: "rating_score"
            type: "slider"
            prompt: "rate:"
            input_choices:
                choice_min: 1
                choice_max: 10
                increments: 1
