default:
    synapse_opts:
        synID:
            parent_output: "syn25614060"
            tbl: "syn22281748" 
        output_filename: "psoriasis_plaque_annotations.tsv"
        column_targets:
            - "psoriasisAreaPhoto.jpg"
            - "psoriasisAreaPhoto.png"
        unique_identifier: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 5
        keep_metadata:
            - "participantID"
            - "createdOn"
    survey_opts:
        survey_1:
            colname: "erythema"
            type: "radio"
            prompt: "Erythema:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_2:
            colname: "induration"
            type: "radio"
            prompt: "Induration:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_3:
            colname: "scaling"
            type: "radio"
            prompt: "Scaling:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
    image_opts: 
        width: "625px"
        height: "425px"
