default:
    mpower_gait:
        survey_1:
            colname: "walk_status"
            prompt: "Can you guess this user's gait?"
            input_choices: 
                initial_choice: "None Selected"
                choice_1: "Walking"
                choice_2: "Mostly Walking"
                choice_3: "Some Walking"
                choice_4: "Not Walking"
                choice_5: "Can't Tell"
        survey_2:
            colname: "pocket_status"
            prompt: "Is this phone inside the pocket?"
            input_choices:
                initial_choice: "None Selected"
                choice_1: "In Pocket"
                choice_2: "Partially in Pocket"
                choice_3: "Not in Pocket"
                choice_4: "Can't Tell"
    psorcast_plaque:
        survey_1:
            colname: "erythema"
            prompt: "erythema"
            input_choices:
                initial_choice: "None Selected"
                choice_1: 0
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4
        survey_2:
            colname: "induration"
            prompt: "induration"
            input_choices:
                initial_choice: "None Selected"
                choice_1: 0
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4
        survey_3:
            colname: "scaling"
            prompt: "scaling"
            input_choices:
                initial_choice: "None Selected"
                choice_1: 0
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4
    psorcast_hand:
        survey_1:
            colname: "prompt1"
            prompt: "prompt1 - testing"
            input_choices:
                initial_choice: "None Selected"
                choice_1: -100
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4
        survey_2:
            colname: "prompt2"
            prompt: "prompt2 -testing 2"
            input_choices:
                initial_choice: "None Selected"
                choice_1: -100
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4
        survey_3:
            colname: "prompt3"
            prompt: "prompt2 -testing 2"
            input_choices:
                initial_choice: "None Selected"
                choice_1: -100
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4
        survey_4:
            colname: "prompt4"
            prompt: "prompt2 -testing 2"
            input_choices:
                initial_choice: "None Selected"
                choice_1: -100
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4
        survey_5:
            colname: "prompt5"
            prompt: "prompt2 -testing 2"
            input_choices:
                initial_choice: "None Selected"
                choice_1: -100
                choice_2: 1
                choice_3: 2
                choice_4: 3
                choice_5: 4