default:
    app_url: NULL
    team_id: NULL
    synapse_opts: NULL
    survey_opts: NULL

# all buttons and used for testing purposes
testing:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-oauth/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn26340454"
        synapse_tbl_id: 
            - "syn22281748" 
        output_filename: 
            - "test_annotations.tsv"
        filehandle_cols:
            - "psoriasisAreaPhoto.jpg"
            - "psoriasisAreaPhoto.png"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 5
        keep_metadata:
            - "participantId"
            - "createdOn"
        sort_keys:
            - "recordId" # optional
    survey_opts:
        survey_1:
                colname: "PGA"
                type: "radio"
                prompt: "PGA:"
                input_choices:
                    0: 0
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    Can't Tell: "Can't Tell"
        survey_2:
            colname: "erythema"
            type: "checkbox_group"
            prompt: "Erythema:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_3:
            colname: "induration"
            type: "slider"
            prompt: "Induration:"
            input_choices:
                min: 0
                max: 5
                step: 1
        survey_4:
            colname: "scaling"
            type: "slider"
            prompt: "Scaling:"
            input_choices:
                min: 0
                max: 5
                step: 1
    image_opts:
        width: "97%"
        height: "97%"

# all buttons and used for testing purposes
psorcast_plaque:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-psorcast-plaque-imaging/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn25614357"
        synapse_tbl_id: 
            - "syn22281748" 
        output_filename: 
            - "psoriasis_plaque_annotations.tsv"
        filehandle_cols:
            - "psoriasisAreaPhoto.jpg"
            - "psoriasisAreaPhoto.png"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 100
        keep_metadata:
            - "participantId"
            - "createdOn"
        sort_keys:
            - "recordId" # optional
    survey_opts:
        survey_1:
                colname: "PGA"
                type: "radio"
                prompt: "PGA:"
                input_choices:
                    0: 0
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    Can't Tell: "Can't Tell"
        survey_2:
            colname: "erythema"
            type: "checkbox_group"
            prompt: "Erythema:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_3:
            colname: "induration"
            type: "checkbox_group"
            prompt: "Induration:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_4:
            colname: "scaling"
            type: "checkbox_group"
            prompt: "Scaling:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
    image_opts:
        width: "97%"
        height: "97%"
                
# psorcast nail
psorcast_nail:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-oauth/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn26133849"
        synapse_tbl_id: 
            - "syn26050060" 
        output_filename: 
            - "nail_psoriasis_annotations.tsv"
        filehandle_cols:
            - "finger_segments"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
            - "finger_key"
        n_batch: 100
        keep_metadata:
            - "participantId"
            - "createdOn"
    survey_opts:
        survey_1:
                colname: "nail_pso_status"
                type: "radio"
                prompt: "Detected Nail Psoriasis:"
                input_choices:
                    Yes: 'TRUE'
                    No: 'FALSE'
                    Unsure: 'Unsure'
                    Can't Tell (Image Quality): "Can't Tell"

# all buttons and used for testing purposes
psorcast_fitzpatrick:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-psorcast-fitzpatrick/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn26433378"
        synapse_tbl_id: 
            - "syn22281749" 
        output_filename: 
            - "handImaging_fitzpatrick_scale.tsv"
        filehandle_cols:
            - "summaryImage.jpg"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 100
        keep_metadata:
            - "participantId"
            - "createdOn"
        sort_keys:
            - "recordId" # optional
    survey_opts:
        survey_1:
                colname: "fitzpatrick_score"
                type: "radio"
                prompt: "Rate Hand Fitzpatrick Score:"
                input_choices:
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    5: 5
                    6: 6
                    Can't Tell: "Can't Tell"
    image_opts:
        width: "97%"
        height: "97%"
# all buttons and used for testing purposes
mpower_gait:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mpower-gait/'
    team_id: '3345548'
    synapse_opts:
        output_parent_id: 
            - "syn26340454"
        synapse_tbl_id: 
            - "syn12514611" 
        output_filename: 
            - "mpower_gait_score.tsv"
        filehandle_cols:
            - "walk_motion.json"
            - "balance_motion.json"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 10
        keep_metadata:
            - "healthCode"
            - "createdOn"
        sort_keys:
            - "recordId" # optional
    survey_opts:
        - colname: "Is this person walking?"
          type: "radio"
          prompt: "Rate Hand Fitzpatrick Score:"
          input_choices:
            Yes: "Yes"
            No: "No"
            Can't Tell: "Can't Tell"
        - colname: "Rate the walking?"
          type: "radio"
          prompt: "Rate Hand Fitzpatrick Score:"
          input_choices:
            - "Walking"
            - "Partially Walking"
            - "Resting"
    image_opts:
        width: "97%"
        height: "97%"