# all buttons and used for testing purposes
default:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-oauth/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn26340454"
        synapse_tbl_id: 
            - "syn22281748" 
        output_filename: 
            - "test_annotations.tsv"
        filehandle_cols:
            - "psoriasisAreaPhoto.jpg"
            - "psoriasisAreaPhoto.png"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 5
        keep_metadata:
            - "participantId"
            - "createdOn"
        sort_keys:
            - "recordId" # optional
    survey_opts:
        survey_1:
                colname: "PGA"
                type: "radio"
                prompt: "PGA:"
                input_choices:
                    0: 0
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    Can't Tell: "Can't Tell"
        survey_2:
            colname: "erythema"
            type: "checkbox_group"
            prompt: "Erythema:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_3:
            colname: "induration"
            type: "slider"
            prompt: "Induration:"
            input_choices:
                min: 0
                max: 5
                step: 1
        survey_4:
            colname: "scaling"
            type: "slider"
            prompt: "Scaling:"
            input_choices:
                min: 0
                max: 5
                step: 1
    image_opts:
        width: "97%"
        height: "97%"

# all buttons and used for testing purposes
psorcast_plaque:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-oauth/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn25614357"
        synapse_tbl_id: 
            - "syn22281748" 
        output_filename: 
            - "psoriasis_plaque_annotations.tsv"
        filehandle_cols:
            - "psoriasisAreaPhoto.jpg"
            - "psoriasisAreaPhoto.png"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 5
        keep_metadata:
            - "participantId"
            - "createdOn"
        sort_keys:
            - "recordId" # optional
    survey_opts:
        survey_1:
                colname: "PGA"
                type: "radio"
                prompt: "PGA:"
                input_choices:
                    0: 0
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    Can't Tell: "Can't Tell"
        survey_2:
            colname: "erythema"
            type: "checkbox_group"
            prompt: "Erythema:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_3:
            colname: "induration"
            type: "slider"
            prompt: "Induration:"
            input_choices:
                min: 0
                max: 5
                step: 1
        survey_4:
            colname: "scaling"
            type: "slider"
            prompt: "Scaling:"
            input_choices:
                min: 0
                max: 5
                step: 1
    image_opts:
        width: "97%"
        height: "97%"
                
# psorcast nail
psorcast_nail:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-oauth/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn26133849"
        synapse_tbl_id: 
            - "syn26159187" 
        output_filename: 
            - "nail_psoriasis_annotations.tsv"
        filehandle_cols:
            - "finger_segments"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
            - "finger_key"
        n_batch: 100
        keep_metadata:
            - "participantId"
            - "createdOn"
    survey_opts:
        survey_1:
                colname: "nail_pso_status"
                type: "radio"
                prompt: "Detected Nail Psoriasis:"
                input_choices:
                    Yes: 'TRUE'
                    No: 'FALSE'
                    Can't Tell: "Can't Tell"

# all buttons and used for testing purposes
psorcast_fitzpatrick:
    app_url: 'https://shinypro.synapse.org/users/atediarjo/mhealthannotator-psorcast-fitzpatrick/'
    team_id: '3425336'
    synapse_opts:
        output_parent_id: 
            - "syn26433378"
        synapse_tbl_id: 
            - "syn22281748" 
        output_filename: 
            - "handImaging_fitzpatrick_scale.tsv"
        filehandle_cols:
            - "summaryImage.jpg"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: 100
        keep_metadata:
            - "participantId"
            - "createdOn"
        sort_keys:
            - "recordId" # optional
    survey_opts:
        survey_1:
                colname: "left_hand_fitzpatrick_score"
                type: "radio"
                prompt: "Rate Left Hand Fitzpatrick Score:"
                input_choices:
                    0: 0
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    5: 5
                    6: 6
                    Can't Tell: "Can't Tell"
        survey_2:
                colname: "right_hand_fitzpatrick_score"
                type: "radio"
                prompt: "Rate Right Hand Fitzpatrick Score:"
                input_choices:
                    0: 0
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    5: 5
                    6: 6
                    Can't Tell: "Can't Tell"
    image_opts:
        width: "97%"
        height: "97%"
