default:
    synapse_opts:
        output_parent_id: 
            - "syn25614357"
        synapse_tbl_id: 
            - "syn22281748" 
        output_filename: 
            - "psoriasis_plaque_annotations.tsv"
        filehandle_cols:
            - "psoriasisAreaPhoto.jpg"
            - "psoriasisAreaPhoto.png"
        uid: 
            - "recordId" # unique identifier for that file in synapse table
        n_batch: a
        keep_metadata:
            - "participantId"
            - "createdOn"
    survey_opts:
        survey_1:
                colname: "PGA"
                type: "radio"
                prompt: "PGA:"
                input_choices:
                    0: 0
                    1: 1
                    2: 2
                    3: 3
                    4: 4
                    Can't Tell: "Can't Tell"
        survey_2:
            colname: "erythema"
            type: "radio"
            prompt: "Erythema:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_3:
            colname: "induration"
            type: "radio"
            prompt: "Induration:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
        survey_4:
            colname: "scaling"
            type: "radio"
            prompt: "Scaling:"
            input_choices:
                0: 0
                1: 1
                2: 2
                3: 3
                4: 4
                Can't Tell: "Can't Tell"
    image_opts:
        width:
        height:
