default:
    synapse_opts:
        synID:
            parent_output: "syn25614059"
            tbl: "syn22281749" 
        output_filename: "psorcast_hand_imaging_annotations.tsv"
        column_targets:
            - "summaryImage.jpg"
        unique_identifier: 
            - "recordId"
        n_batch: 3
        keep_metadata:
            - "participantId"
            - "createdOn"
    survey_opts:
        survey_1:
            colname: "left_nail_psoriasis"
            type: "checkbox_group"
            prompt: "Select Left-Hand Nail Psoriasis:"
            selected: "None"
            input_choices:
                - "None"
                - "L1"
                - "L2"
                - "L3"
                - "L4"
                - "L5"
        survey_2:
            colname: "right_nail_psoriasis"
            type: "checkbox_group"
            prompt: "Select Right-Hand Nail Psoriasis:"
            selected: "None"
            input_choices:
                - "None"
                - "R1"
                - "R2"
                - "R3"
                - "R4"
                - "R5"
    image_opts: 
        width: "95%"
        height: "95%"
